#!/bin/bash

# DB-Taxi Setup Wizard
echo "🚀 DB-Taxi MySQL Web Explorer - Setup Wizard"
echo "=============================================="
echo ""

# Check if config.yaml already exists
if [ -f "config.yaml" ]; then
    echo "⚠️  config.yaml already exists."
    read -p "Do you want to overwrite it? (y/N): " overwrite
    if [[ ! $overwrite =~ ^[Yy]$ ]]; then
        echo "Setup cancelled. Using existing config.yaml"
        exit 0
    fi
fi

echo "This wizard will help you create a configuration file for DB-Taxi."
echo ""

# Database configuration
echo "📊 Database Configuration"
echo "------------------------"
read -p "MySQL Host (default: localhost): " db_host
db_host=${db_host:-localhost}

read -p "MySQL Port (default: 3306): " db_port
db_port=${db_port:-3306}

read -p "MySQL Username (default: root): " db_username
db_username=${db_username:-root}

read -s -p "MySQL Password: " db_password
echo ""

read -p "Database Name (optional): " db_database

read -p "Enable SSL? (y/N): " db_ssl
if [[ $db_ssl =~ ^[Yy]$ ]]; then
    db_ssl="true"
else
    db_ssl="false"
fi

echo ""

# Server configuration
echo "🌐 Server Configuration"
echo "----------------------"
read -p "Server Port (default: 8080): " server_port
server_port=${server_port:-8080}

read -p "Server Host (default: 0.0.0.0): " server_host
server_host=${server_host:-0.0.0.0}

echo ""

# Security configuration
echo "🔒 Security Configuration"
echo "-------------------------"
read -p "Enable Read-Only Mode? (y/N): " readonly_mode
if [[ $readonly_mode =~ ^[Yy]$ ]]; then
    readonly_mode="true"
else
    readonly_mode="false"
fi

read -p "Session Timeout in minutes (default: 30): " session_timeout
session_timeout=${session_timeout:-30}

echo ""

# Logging configuration
echo "📝 Logging Configuration"
echo "------------------------"
echo "Log levels: debug, info, warn, error"
read -p "Log Level (default: info): " log_level
log_level=${log_level:-info}

echo "Log formats: json, text"
read -p "Log Format (default: json): " log_format
log_format=${log_format:-json}

echo ""

# Generate configuration file
echo "📄 Generating config.yaml..."

cat > config.yaml << EOF
# DB-Taxi Configuration
# Generated by setup wizard on $(date)

server:
  port: $server_port
  host: "$server_host"
  read_timeout: "30s"
  write_timeout: "30s"
  enable_https: false

database:
  host: "$db_host"
  port: $db_port
  username: "$db_username"
  password: "$db_password"
  database: "$db_database"
  ssl: $db_ssl
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"
  query_timeout: "30s"

security:
  session_timeout: "${session_timeout}m"
  read_only_mode: $readonly_mode
  enable_audit: true

logging:
  level: "$log_level"
  format: "$log_format"
  output: "stdout"
  max_size: 100
  max_backups: 3
  max_age: 28
EOF

echo "✅ Configuration file created: config.yaml"
echo ""

# Test database connection
echo "🔍 Testing database connection..."
if command -v mysql &> /dev/null; then
    if mysql -h "$db_host" -P "$db_port" -u "$db_username" -p"$db_password" -e "SELECT 1;" &> /dev/null; then
        echo "✅ Database connection successful!"
    else
        echo "⚠️  Database connection failed. Please check your credentials."
        echo "   You can still run DB-Taxi, but it will show connection errors."
    fi
else
    echo "ℹ️  MySQL client not found. Skipping connection test."
fi

echo ""

# Build and run options
echo "🚀 Next Steps"
echo "-------------"
echo "1. Build the application:"
echo "   go build -o db-taxi ."
echo ""
echo "2. Run DB-Taxi:"
echo "   ./db-taxi"
echo ""
echo "3. Access the web interface:"
echo "   http://$server_host:$server_port"
echo ""
echo "4. Alternative: Run with custom config:"
echo "   ./db-taxi -config config.yaml"
echo ""

# Ask if user wants to build and run now
read -p "Would you like to build and run DB-Taxi now? (y/N): " build_run
if [[ $build_run =~ ^[Yy]$ ]]; then
    echo ""
    echo "📦 Building DB-Taxi..."
    if go build -o db-taxi .; then
        echo "✅ Build successful!"
        echo ""
        echo "🚀 Starting DB-Taxi..."
        echo "   Press Ctrl+C to stop"
        echo "   Web interface: http://$server_host:$server_port"
        echo ""
        ./db-taxi
    else
        echo "❌ Build failed. Please check for errors and try again."
        exit 1
    fi
else
    echo ""
    echo "🎉 Setup complete! You can now build and run DB-Taxi manually."
fi